### ISSUE TITLE
Support for custom biomes

### ISSUE THREAD

**Issue by URSFR** [Happy-Hop7/RealisticPlantGrowth#12]
im trying to use this plugin with Terra and RealisticSeasons plugins but it doesnt work

![custom](https://github.com/Happy-Hop7/RealisticPlantGrowth/assets/97409596/3d6c80fe-9372-4fc1-97d4-23ca098620d2)

**Comment by Happy-Hop7** [comment]
Support for custom biomes added in 9f8bf0badf460d862b5931d3c8c5b7c682b350a5.
